version: "3.8"

services:
  web-node:
    image: svelte-docker-node
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:3000
    environment:
      AMQP_HOST: ${AMQP_HOST}
      AMQP_PORT: ${AMQP_PORT}
      AMQP_USERNAME: ${AMQP_USERNAME}
      AMQP_PASSWORD: ${AMQP_PASSWORD}
      ORIGIN: ${WEB_ORIGIN}
  worker:
    image: python-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      AMQP_HOST: ${AMQP_HOST}
      AMQP_PORT: ${AMQP_PORT}
      AMQP_USERNAME: ${AMQP_USERNAME}
      AMQP_PASSWORD: ${AMQP_PASSWORD}
