version: "3.8"

services:
  web-node:
    image: svelte-docker-node
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:3000
    environment:
      AMQP_HOST: message-queue
      AMQP_PORT: 5672
      AMQP_USERNAME: ${AMQP_USERNAME}
      AMQP_PASSWORD: ${AMQP_PASSWORD}
      ORIGIN: ${WEB_ORIGIN}
    depends_on:
      - message-queue
    restart: always
  worker-add:
    image: python-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
      args:
        - WORKER=add
    environment:
      AMQP_HOST: message-queue
      AMQP_PORT: 5672
      AMQP_USERNAME: ${AMQP_USERNAME}
      AMQP_PASSWORD: ${AMQP_PASSWORD}
    depends_on:
      - message-queue
    restart: always
  worker-plate-solving:
    image: python-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
      args:
        - WORKER=plate-solving
    environment:
      AMQP_HOST: message-queue
      AMQP_PORT: 5672
      AMQP_USERNAME: ${AMQP_USERNAME}
      AMQP_PASSWORD: ${AMQP_PASSWORD}
    depends_on:
      - message-queue
    restart: always
  message-queue:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    ports:
      # HTTP management UI
      - 15672:15672
